// Catalog of common lab markers: ru / uk / en names, abbreviation and extra search aliases.
window.GROUPS = [
  ["blood", "Кровь"],
  ["coag", "Свёртываемость"],
  ["bio", "Биохимия"],
  ["lipid", "Липиды"],
  ["iron", "Витамины"],
  ["thyroid", "Щитовидка"],
  ["hormone", "Гормоны"],
  ["immune", "Воспаление и иммунитет"],
  ["infect", "Инфекции"],
  ["gi", "ЖКТ"],
  ["urine", "Моча"],
  ["vitals", "Давление"],
  ["other", "Другое"],
];

const C = (id, group, ru, uk, en, abbr, unit, extra = "") => ({ id, group, ru, uk, en, abbr, unit, extra });

window.CATALOG = [
  C("hgb", "blood", "Гемоглобин", "Гемоглобін", "Hemoglobin", "HGB", "г/л", "hb"),
  C("hct", "blood", "Гематокрит", "Гематокрит", "Hematocrit", "HCT", "%"),
  C("rbc", "blood", "Эритроциты", "Еритроцити", "Red blood cells", "RBC", "10¹²/л"),
  C("wbc", "blood", "Лейкоциты", "Лейкоцити", "White blood cells", "WBC", "10⁹/л"),
  C("plt", "blood", "Тромбоциты", "Тромбоцити", "Platelets", "PLT", "10⁹/л"),
  C("esr", "blood", "СОЭ", "ШОЕ", "Erythrocyte sedimentation rate", "ESR", "мм/ч", "скорость оседания швидкість осідання"),
  C("neut", "blood", "Нейтрофилы", "Нейтрофіли", "Neutrophils", "NEUT", "%"),
  C("lymph", "blood", "Лимфоциты", "Лімфоцити", "Lymphocytes", "LYMPH", "%"),
  C("mono", "blood", "Моноциты", "Моноцити", "Monocytes", "MONO", "%"),
  C("eos", "blood", "Эозинофилы", "Еозинофіли", "Eosinophils", "EOS", "%"),
  C("mcv", "blood", "Средний объём эритроцита", "Середній об'єм еритроцита", "Mean corpuscular volume", "MCV", "фл"),
  C("glu", "bio", "Глюкоза", "Глюкоза", "Glucose", "GLU", "ммоль/л", "сахар цукор"),
  C("hba1c", "bio", "Гликированный гемоглобин", "Глікований гемоглобін", "Glycated hemoglobin", "HbA1c", "%"),
  C("alt", "bio", "АЛТ", "АЛТ", "Alanine aminotransferase", "ALT", "Ед/л", "аланинаминотрансфераза аланінамінотрансфераза"),
  C("ast", "bio", "АСТ", "АСТ", "Aspartate aminotransferase", "AST", "Ед/л", "аспартатаминотрансфераза аспартатамінотрансфераза"),
  C("ggt", "bio", "ГГТ", "ГГТ", "Gamma-glutamyl transferase", "GGT", "Ед/л", "гаммаглутамилтрансфераза глутаматтрансфераза"),
  C("alp", "bio", "Щелочная фосфатаза", "Лужна фосфатаза", "Alkaline phosphatase", "ALP", "Ед/л"),
  C("tbil", "bio", "Билирубин общий", "Білірубін загальний", "Total bilirubin", "TBIL", "мкмоль/л"),
  C("dbil", "bio", "Билирубин прямой", "Білірубін прямий", "Direct bilirubin", "DBIL", "мкмоль/л"),
  C("tp", "bio", "Общий белок", "Загальний білок", "Total protein", "TP", "г/л"),
  C("alb", "bio", "Альбумин", "Альбумін", "Albumin", "ALB", "г/л"),
  C("urea", "bio", "Мочевина", "Сечовина", "Urea", "BUN", "ммоль/л"),
  C("crea", "bio", "Креатинин", "Креатинін", "Creatinine", "CREA", "мкмоль/л"),
  C("ua", "bio", "Мочевая кислота", "Сечова кислота", "Uric acid", "UA", "мкмоль/л"),
  C("crp", "bio", "С-реактивный белок", "С-реактивний білок", "C-reactive protein", "CRP", "мг/л", "срб срп"),
  C("amy", "bio", "Амилаза", "Амілаза", "Amylase", "AMY", "Ед/л"),
  C("chol", "lipid", "Холестерин общий", "Холестерин загальний", "Total cholesterol", "TC", "ммоль/л", "холестерол cholesterol"),
  C("tg", "lipid", "Триглицериды", "Тригліцериди", "Triglycerides", "TG", "ммоль/л"),
  C("hdl", "lipid", "ЛПВП", "ЛПВЩ", "HDL cholesterol", "HDL", "ммоль/л", "липопротеины высокой плотности ліпопротеїди високої щільності"),
  C("ldl", "lipid", "ЛПНП", "ЛПНЩ", "LDL cholesterol", "LDL", "ммоль/л", "липопротеины низкой плотности ліпопротеїди низької щільності ldlc"),
  C("vldl", "lipid", "ЛПОНП", "ЛПДНЩ", "VLDL cholesterol", "VLDL", "ммоль/л", "липопротеины очень низкой плотности"),
  C("ai", "lipid", "Коэффициент атерогенности", "Коефіцієнт атерогенності", "Atherogenic index", "AI", "", "ка"),
  C("apoa1", "lipid", "Аполипопротеин А-1", "Аполіпопротеїн А-1", "Apolipoprotein A1", "ApoA1", "г/л"),
  C("apob", "lipid", "Аполипопротеин B", "Аполіпопротеїн B", "Apolipoprotein B", "ApoB", "г/л"),
  C("fe", "iron", "Железо сывороточное", "Залізо сироваткове", "Serum iron", "Fe", "мкмоль/л"),
  C("ferritin", "iron", "Ферритин", "Феритин", "Ferritin", "FER", "нг/мл"),
  C("tibc", "iron", "ОЖСС", "ЗЗЗС", "Total iron-binding capacity", "TIBC", "мкмоль/л"),
  C("b12", "iron", "Витамин B12", "Вітамін B12", "Vitamin B12", "B12", "пг/мл", "кобаламин кобаламін б12"),
  C("folate", "iron", "Фолиевая кислота", "Фолієва кислота", "Folate", "FOL", "нг/мл", "фолат b9"),
  C("vitd", "iron", "Витамин D (25-OH)", "Вітамін D (25-OH)", "Vitamin D, 25-hydroxy", "25(OH)D", "нг/мл", "д3 d3"),
  C("zn", "iron", "Цинк", "Цинк", "Zinc", "Zn", "мкмоль/л"),
  C("cu", "iron", "Медь", "Мідь", "Copper", "Cu", "мкмоль/л"),
  C("mg", "iron", "Магний", "Магній", "Magnesium", "Mg", "ммоль/л"),
  C("ca", "iron", "Кальций", "Кальцій", "Calcium", "Ca", "ммоль/л"),
  C("k", "iron", "Калий", "Калій", "Potassium", "K", "ммоль/л"),
  C("na", "iron", "Натрий", "Натрій", "Sodium", "Na", "ммоль/л"),
  C("p", "iron", "Фосфор", "Фосфор", "Phosphorus", "P", "ммоль/л"),
  C("tsh", "thyroid", "ТТГ", "ТТГ", "Thyroid-stimulating hormone", "TSH", "мкМЕ/мл", "тиреотропный тиреотропний"),
  C("ft4", "thyroid", "Т4 свободный", "Т4 вільний", "Free thyroxine", "FT4", "пмоль/л", "тироксин t4"),
  C("ft3", "thyroid", "Т3 свободный", "Т3 вільний", "Free triiodothyronine", "FT3", "пг/мл", "трийодтиронин трийодтиронін t3"),
  C("atpo", "thyroid", "АТ-ТПО", "АТПО", "Anti-thyroid peroxidase antibodies", "Anti-TPO", "МЕ/мл", "антитела к тиреопероксидазе пероксидаза антитіла тпо tpo"),
  C("attg", "thyroid", "АТ-ТГ", "АТТГ", "Anti-thyroglobulin antibodies", "Anti-TG", "МЕ/мл", "антитела к тиреоглобулину тиреоглобулін tgab"),
  C("testo", "hormone", "Тестостерон общий", "Тестостерон загальний", "Total testosterone", "TT", "нмоль/л"),
  C("ftesto", "hormone", "Тестостерон свободный", "Тестостерон вільний", "Free testosterone", "FT", "пг/мл"),
  C("shbg", "hormone", "ГСПГ", "ГЗСС", "Sex hormone-binding globulin", "SHBG", "нмоль/л", "глобулин связывающий половые гормоны глобулін"),
  C("e2", "hormone", "Эстрадиол", "Естрадіол", "Estradiol", "E2", "пг/мл"),
  C("prl", "hormone", "Пролактин", "Пролактин", "Prolactin", "PRL", "нг/мл"),
  C("fsh", "hormone", "ФСГ", "ФСГ", "Follicle-stimulating hormone", "FSH", "мМЕ/мл", "фолликулостимулирующий фолікулостимулюючий"),
  C("lh", "hormone", "ЛГ", "ЛГ", "Luteinizing hormone", "LH", "мМЕ/мл", "лютеинизирующий лютеїнізуючий"),
  C("cort", "hormone", "Кортизол", "Кортизол", "Cortisol", "CORT", "нмоль/л"),
  C("ins", "hormone", "Инсулин", "Інсулін", "Insulin", "INS", "мкЕд/мл"),
  C("dheas", "hormone", "ДГЭА-С", "ДГЕА-С", "DHEA sulfate", "DHEA-S", "мкг/дл"),
  C("sbp", "vitals", "Давление верхнее", "Тиск систолічний", "Systolic blood pressure", "SYS", "мм рт. ст.", "систолическое давление тиск"),
  C("dbp", "vitals", "Давление нижнее", "Тиск діастолічний", "Diastolic blood pressure", "DIA", "мм рт. ст.", "диастолическое давление тиск"),
  C("hr", "vitals", "Пульс", "Пульс", "Heart rate", "HR", "уд/мин", "чсс"),
];


// More markers: shown in the "not taken yet" section and in the entry form.
window.CATALOG.push(
  C("baso", "blood", "Базофилы", "Базофіли", "Basophils", "BASO", "%"),
  C("mch", "blood", "Среднее содержание гемоглобина", "Середній вміст гемоглобіну", "Mean corpuscular hemoglobin", "MCH", "пг"),
  C("mchc", "blood", "Средняя концентрация гемоглобина", "Середня концентрація гемоглобіну", "Mean corpuscular hemoglobin concentration", "MCHC", "г/л"),
  C("rdw", "blood", "Ширина распределения эритроцитов (CV)", "Ширина розподілу еритроцитів (CV)", "Red cell distribution width, CV", "RDW-CV", "%"),
  C("rdw_sd", "blood", "Ширина распределения эритроцитов (SD)", "Ширина розподілу еритроцитів (SD)", "Red cell distribution width, SD", "RDW-SD", "фл"),
  C("mpv", "blood", "Средний объём тромбоцитов", "Середній об'єм тромбоцитів", "Mean platelet volume", "MPV", "фл"),
  C("pdw", "blood", "Ширина распределения тромбоцитов", "Ширина розподілу тромбоцитів", "Platelet distribution width", "PDW", "фл"),
  C("pct", "blood", "Тромбокрит", "Тромбокрит", "Plateletcrit", "PCT", "%"),
  C("neut_abs", "blood", "Нейтрофилы, абс.", "Нейтрофіли, абс.", "Neutrophils, absolute", "NEUT#", "10⁹/л"),
  C("lymph_abs", "blood", "Лимфоциты, абс.", "Лімфоцити, абс.", "Lymphocytes, absolute", "LYMPH#", "10⁹/л"),
  C("mono_abs", "blood", "Моноциты, абс.", "Моноцити, абс.", "Monocytes, absolute", "MONO#", "10⁹/л"),
  C("eos_abs", "blood", "Эозинофилы, абс.", "Еозинофіли, абс.", "Eosinophils, absolute", "EOS#", "10⁹/л"),
  C("baso_abs", "blood", "Базофилы, абс.", "Базофіли, абс.", "Basophils, absolute", "BASO#", "10⁹/л"),
  C("ig", "blood", "Незрелые гранулоциты", "Незрілі гранулоцити", "Immature granulocytes", "IG%", "%"),
  C("ig_abs", "blood", "Незрелые гранулоциты, абс.", "Незрілі гранулоцити, абс.", "Immature granulocytes, absolute", "IG#", "10⁹/л"),
  C("retic", "blood", "Ретикулоциты", "Ретикулоцити", "Reticulocytes", "RET", "%"),
  C("pt", "coag", "Протромбиновое время", "Протромбіновий час", "Prothrombin time", "PT", "с"),
  C("inr", "coag", "МНО", "МНВ", "International normalized ratio", "INR", ""),
  C("pti", "coag", "ПТИ", "ПТІ", "Prothrombin index", "PTI", "%", "протромбиновый индекс протромбіновий індекс"),
  C("aptt", "coag", "АЧТВ", "АЧТЧ", "Activated partial thromboplastin time", "aPTT", "с"),
  C("fib", "coag", "Фибриноген", "Фібриноген", "Fibrinogen", "FIB", "г/л"),
  C("ddimer", "coag", "Д-димер", "Д-димер", "D-dimer", "D-dimer", "нг/мл"),
  C("ibil", "bio", "Билирубин непрямой", "Білірубін непрямий", "Indirect bilirubin", "IBIL", "мкмоль/л"),
  C("ck", "bio", "Креатинфосфокиназа", "Креатинфосфокіназа", "Creatine kinase", "CK", "Ед/л", "кфк"),
  C("ldh", "bio", "ЛДГ", "ЛДГ", "Lactate dehydrogenase", "LDH", "Ед/л", "лактатдегидрогеназа лактатдегідрогеназа"),
  C("lipase", "bio", "Липаза", "Ліпаза", "Lipase", "LPS", "Ед/л"),
  C("cpep", "bio", "С-пептид", "С-пептид", "C-peptide", "C-pep", "нг/мл"),
  C("homa", "bio", "Индекс HOMA-IR", "Індекс HOMA-IR", "HOMA-IR", "HOMA", "", "инсулинорезистентность інсулінорезистентність"),
  C("homocys", "bio", "Гомоцистеин", "Гомоцистеїн", "Homocysteine", "HCY", "мкмоль/л"),
  C("egfr", "bio", "СКФ", "ШКФ", "Estimated glomerular filtration rate", "eGFR", "мл/мин/1,73м²", "скорость клубочковой фильтрации швидкість клубочкової фільтрації"),
  C("cystc", "bio", "Цистатин C", "Цистатин C", "Cystatin C", "CysC", "мг/л"),
  C("lpa", "lipid", "Липопротеин (а)", "Ліпопротеїн (а)", "Lipoprotein(a)", "Lp(a)", "мг/дл"),
  C("nonhdl", "lipid", "Холестерин не-ЛПВП", "Холестерин не-ЛПВЩ", "Non-HDL cholesterol", "non-HDL", "ммоль/л"),
  C("transf", "iron", "Трансферрин", "Трансферин", "Transferrin", "TRF", "г/л"),
  C("tsat", "iron", "Насыщение трансферрина", "Насичення трансферину", "Transferrin saturation", "TSAT", "%"),
  C("cl", "iron", "Хлор", "Хлор", "Chloride", "Cl", "ммоль/л"),
  C("vita", "iron", "Витамин A", "Вітамін A", "Vitamin A", "Vit A", "мкмоль/л", "ретинол"),
  C("vite", "iron", "Витамин E", "Вітамін E", "Vitamin E", "Vit E", "мкмоль/л", "токоферол"),
  C("b6", "iron", "Витамин B6", "Вітамін B6", "Vitamin B6", "B6", "нмоль/л", "пиридоксин піридоксин"),
  C("b1", "iron", "Витамин B1", "Вітамін B1", "Vitamin B1", "B1", "нмоль/л", "тиамин тіамін"),
  C("se", "iron", "Селен", "Селен", "Selenium", "Se", "мкмоль/л"),
  C("omega3", "iron", "Омега-3 индекс", "Омега-3 індекс", "Omega-3 index", "O3I", "%"),
  C("tt4", "thyroid", "Т4 общий", "Т4 загальний", "Total thyroxine", "TT4", "нмоль/л"),
  C("tt3", "thyroid", "Т3 общий", "Т3 загальний", "Total triiodothyronine", "TT3", "нмоль/л"),
  C("trab", "thyroid", "АТ к рецепторам ТТГ", "АТ до рецепторів ТТГ", "TSH receptor antibodies", "TRAb", "МЕ/л"),
  C("thyroglob", "thyroid", "Тиреоглобулин", "Тиреоглобулін", "Thyroglobulin", "Tg", "нг/мл"),
  C("calcit", "thyroid", "Кальцитонин", "Кальцитонін", "Calcitonin", "CT", "пг/мл"),
  C("prog", "hormone", "Прогестерон", "Прогестерон", "Progesterone", "P4", "нмоль/л"),
  C("oh17", "hormone", "17-ОН прогестерон", "17-ОН прогестерон", "17-hydroxyprogesterone", "17-OHP", "нмоль/л"),
  C("dht", "hormone", "Дигидротестостерон", "Дигідротестостерон", "Dihydrotestosterone", "DHT", "пг/мл"),
  C("acth", "hormone", "АКТГ", "АКТГ", "Adrenocorticotropic hormone", "ACTH", "пг/мл", "адренокортикотропный адренокортикотропний"),
  C("pth", "hormone", "Паратгормон", "Паратгормон", "Parathyroid hormone", "PTH", "пг/мл"),
  C("igf1", "hormone", "ИФР-1", "ІФР-1", "Insulin-like growth factor 1", "IGF-1", "нг/мл", "соматомедин"),
  C("gh", "hormone", "Гормон роста", "Гормон росту", "Growth hormone", "GH", "нг/мл", "стг соматотропин соматотропін"),
  C("mprl", "hormone", "Макропролактин", "Макропролактин", "Macroprolactin", "mPRL", "%"),
  C("cort_s", "hormone", "Кортизол в слюне", "Кортизол у слині", "Salivary cortisol", "sCORT", "нмоль/л"),
  C("aldo", "hormone", "Альдостерон", "Альдостерон", "Aldosterone", "ALD", "пг/мл"),
  C("renin", "hormone", "Ренин", "Ренін", "Renin", "REN", "мкМЕ/мл"),
  C("psa", "hormone", "ПСА общий", "ПСА загальний", "Prostate-specific antigen", "PSA", "нг/мл"),
  C("amh", "hormone", "Антимюллеров гормон", "Антимюлерів гормон", "Anti-Müllerian hormone", "АМГ", "нг/мл", "amh овариальный резерв"),
  C("hscrp", "immune", "вч-СРБ", "вч-СРБ", "High-sensitivity C-reactive protein", "hs-CRP", "мг/л", "высокочувствительный"),
  C("ige", "immune", "IgE общий", "IgE загальний", "Total IgE", "IgE", "МЕ/мл"),
  C("rf", "immune", "Ревматоидный фактор", "Ревматоїдний фактор", "Rheumatoid factor", "RF", "МЕ/мл"),
  C("aso", "immune", "АСЛ-О", "АСЛ-О", "Antistreptolysin O", "ASO", "МЕ/мл"),
  C("ana", "immune", "Антинуклеарные антитела", "Антинуклеарні антитіла", "Antinuclear antibodies", "ANA", ""),
  C("accp", "immune", "Антитела к циклическому цитруллинированному пептиду", "Антитіла до циклічного цитрулінованого пептиду", "Anti-CCP antibodies", "АЦЦП", "Ед/мл", "anti-ccp ревматоидный"),
  C("hbsag", "infect", "HBsAg (гепатит B)", "HBsAg (гепатит B)", "Hepatitis B surface antigen", "HBsAg", ""),
  C("hcv", "infect", "Антитела к гепатиту C", "Антитіла до гепатиту C", "Hepatitis C antibodies", "anti-HCV", ""),
  C("hiv", "infect", "ВИЧ 1/2", "ВІЛ 1/2", "HIV 1/2 antigen/antibody", "HIV", ""),
  C("syph", "infect", "Сифилис", "Сифіліс", "Syphilis antibodies", "RW", "", "реакция вассермана"),
  C("hp_igg", "infect", "Хеликобактер IgG", "Хелікобактер IgG", "Helicobacter pylori IgG", "HP IgG", "", "helicobacter хелик"),
  C("hp_ubt", "infect", "Дыхательный тест на хеликобактер", "Дихальний тест на хелікобактер", "Urea breath test", "UBT", "", "helicobacter хелик"),
  C("hp_ag", "infect", "Хеликобактер: антиген в кале", "Хелікобактер: антиген у калі", "H. pylori stool antigen", "HpSA", "", "helicobacter хелик"),
  C("ebv", "infect", "Вирус Эпштейна–Барр IgG", "Вірус Епштейна–Барр IgG", "Epstein–Barr virus VCA IgG", "EBV", "", "вэб веб"),
  C("cmv", "infect", "Цитомегаловирус IgG", "Цитомегаловірус IgG", "Cytomegalovirus IgG", "CMV", "", "цмв"),
  C("fcal", "gi", "Кальпротектин", "Кальпротектин", "Fecal calprotectin", "FC", "мкг/г"),
  C("ttg_iga", "gi", "Антитела к тканевой трансглутаминазе IgA", "Антитіла до тканинної трансглутамінази IgA", "Tissue transglutaminase IgA", "tTG-IgA", "Ед/мл", "целиакия глютен celiac"),
  C("fob", "gi", "Скрытая кровь в кале", "Прихована кров у калі", "Fecal occult blood", "FOBT", ""),
  C("elast", "gi", "Панкреатическая эластаза", "Панкреатична еластаза", "Pancreatic elastase", "E1", "мкг/г"),
  C("coprog", "gi", "Копрограмма", "Копрограма", "Stool analysis", "", "", "кал"),
  C("u_sg", "urine", "Удельный вес мочи", "Питома вага сечі", "Urine specific gravity", "SG", ""),
  C("u_ph", "urine", "pH мочи", "pH сечі", "Urine pH", "pH", ""),
  C("u_prot", "urine", "Белок в моче", "Білок у сечі", "Urine protein", "PRO", "г/л"),
  C("u_glu", "urine", "Глюкоза в моче", "Глюкоза в сечі", "Urine glucose", "GLU", "ммоль/л"),
  C("u_wbc", "urine", "Лейкоциты в моче", "Лейкоцити в сечі", "Urine white blood cells", "LEU", "в п/зр"),
  C("u_rbc", "urine", "Эритроциты в моче", "Еритроцити в сечі", "Urine red blood cells", "ERY", "в п/зр"),
  C("u_alb", "urine", "Микроальбумин в моче", "Мікроальбумін у сечі", "Urine microalbumin", "MAU", "мг/л"),
  C("weight", "vitals", "Вес", "Вага", "Body weight", "", "кг"),
  C("bmi", "vitals", "Индекс массы тела", "Індекс маси тіла", "Body mass index", "BMI", "кг/м²", "имт імт"),
  C("spo2", "vitals", "Сатурация", "Сатурація", "Oxygen saturation", "SpO2", "%"),
  C("temp", "vitals", "Температура тела", "Температура тіла", "Body temperature", "", "°C"),
);

// ---------- Units ----------
// Every spelling a lab might print maps to one token. Values are stored exactly as on the blank
// and converted to the marker's main unit only for display.
window.UNIT_TOKENS = {
  mmol_l: ["ммоль/л", "mmol/l"],
  umol_l: ["мкмоль/л", "µmol/l", "μmol/l", "umol/l"],
  nmol_l: ["нмоль/л", "nmol/l"],
  pmol_l: ["пмоль/л", "pmol/l"],
  g_l: ["г/л", "g/l"],
  g_dl: ["г/дл", "g/dl"],
  mg_dl: ["мг/дл", "mg/dl", "мг%"],
  mg_l: ["мг/л", "mg/l"],
  ug_dl: ["мкг/дл", "µg/dl", "μg/dl", "ug/dl", "мкг%"],
  ng_dl: ["нг/дл", "ng/dl"],
  ng_ml: ["нг/мл", "ng/ml", "мкг/л", "µg/l", "μg/l", "ug/l"],
  pg_ml: ["пг/мл", "pg/ml", "нг/л", "ng/l"],
  miu_l: ["мкме/мл", "мкмо/мл", "мкед/мл", "мкод/мл", "µiu/ml", "μiu/ml", "uiu/ml", "µu/ml", "μu/ml", "uu/ml", "мме/л", "ммо/л", "мед/л", "miu/l", "mu/l"],
  iu_ml: ["ме/мл", "мо/мл", "ед/мл", "од/мл", "iu/ml", "u/ml"],
  iu_l: ["мме/мл", "ммо/мл", "мед/мл", "miu/ml", "ме/л", "мо/л", "ед/л", "од/л", "iu/l", "u/l"],
  pct: ["%"],
  mmhg: ["мм рт. ст.", "мм рт.ст.", "ммртст", "mmhg"],
  bpm: ["уд/мин", "bpm"],
};

// Main unit per marker (token) and factors: value_in_main = value * factor.
window.UNIT_CONV = {
  hgb: ["g_l", { g_dl: 10 }],
  mchc: ["g_l", { g_dl: 10 }],
  glu: ["mmol_l", { mg_dl: 1 / 18.016 }],
  tbil: ["umol_l", { mg_dl: 17.104 }],
  dbil: ["umol_l", { mg_dl: 17.104 }],
  tp: ["g_l", { g_dl: 10 }],
  alb: ["g_l", { g_dl: 10 }],
  urea: ["mmol_l", { mg_dl: 0.357 }],
  crea: ["umol_l", { mg_dl: 88.42 }],
  ua: ["umol_l", { mg_dl: 59.48 }],
  crp: ["mg_l", { mg_dl: 10 }],
  chol: ["mmol_l", { mg_dl: 1 / 38.67 }],
  hdl: ["mmol_l", { mg_dl: 1 / 38.67 }],
  ldl: ["mmol_l", { mg_dl: 1 / 38.67 }],
  vldl: ["mmol_l", { mg_dl: 1 / 38.67 }],
  tg: ["mmol_l", { mg_dl: 1 / 88.57 }],
  apoa1: ["g_l", { mg_dl: 0.01 }],
  apob: ["g_l", { mg_dl: 0.01 }],
  fe: ["umol_l", { ug_dl: 0.1791 }],
  ferritin: ["ng_ml", {}],
  tibc: ["umol_l", { ug_dl: 0.1791 }],
  b12: ["pg_ml", { pmol_l: 1 / 0.7378 }],
  folate: ["ng_ml", { nmol_l: 1 / 2.266 }],
  vitd: ["ng_ml", { nmol_l: 1 / 2.496 }],
  mg: ["mmol_l", { mg_dl: 1 / 2.431 }],
  ca: ["mmol_l", { mg_dl: 1 / 4.008 }],
  p: ["mmol_l", { mg_dl: 1 / 3.097 }],
  tsh: ["miu_l", {}],
  ft4: ["pmol_l", { ng_dl: 12.871, pg_ml: 1.2871 }],
  ft3: ["pg_ml", { pmol_l: 1 / 1.536 }],
  atpo: ["iu_ml", {}],
  attg: ["iu_ml", {}],
  testo: ["nmol_l", { ng_dl: 0.03467, ng_ml: 3.467 }],
  ftesto: ["pg_ml", { pmol_l: 1 / 3.467 }],
  shbg: ["nmol_l", {}],
  e2: ["pg_ml", { pmol_l: 1 / 3.671 }],
  prl: ["ng_ml", { miu_l: 1 / 21.2 }],
  fsh: ["iu_l", {}],
  lh: ["iu_l", {}],
  cort: ["nmol_l", { ug_dl: 27.59 }],
  cort_s: ["ug_dl", { nmol_l: 1 / 27.59 }],
  ins: ["miu_l", { pmol_l: 1 / 6 }],
  dheas: ["ug_dl", { umol_l: 36.81 }],
};

window.UNIT_LABEL = {
  mmol_l: "ммоль/л", umol_l: "мкмоль/л", nmol_l: "нмоль/л", pmol_l: "пмоль/л", g_l: "г/л", g_dl: "г/дл",
  mg_dl: "мг/дл", mg_l: "мг/л", ug_dl: "мкг/дл", ng_dl: "нг/дл", ng_ml: "нг/мл", pg_ml: "пг/мл",
  miu_l: "мкМЕ/мл", iu_ml: "МЕ/мл", iu_l: "мМЕ/мл", pct: "%", mmhg: "мм рт. ст.", bpm: "уд/мин",
};
